name: TESTAR Chromedriver Test

on:
 workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - macos-14-arm64
          - macos-15-arm64
          - ubuntu-22.04
          - windows-latest  # Add or modify OS as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this to '17' or '21' if needed

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "macos-14-arm64" ]]; then
            brew install gradle  # Ensure Gradle is installed on macOS
          elif [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
            sudo apt-get update
            sudo apt-get install -y gradle  # Install Gradle on Ubuntu
          fi

      - name: Initialize and build TESTAR
        run: |
          cd TESTAR_dev
          ./gradlew init_workflow_test
          ./gradlew build
          ./gradlew installDist

      - name: Run Chromedriver test
        run: |
          cd TESTAR_dev
          ./gradlew runTestWebdriverSuspiciousTagMacOS

      - name: Check for widget detection
        run: |
          # Here you might want to check logs or results to confirm widget detection
          # Adjust based on your specific output
          if grep -q 'Forum' ./path/to/logfile; then
            echo "Widget detected successfully."
          else
            echo "Widget detection failed."
            exit 1
          fi
